// Command schemagen generates JSON Schema strings from Go struct types in the
// schemas package and writes them as Go constants to schemas/generated.go.
//
// Usage:
//
//	go run ./cmd/schemagen
//
// The tool is invoked via go:generate (see schemas/gen.go).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/decko/soda/schemas"
)

// registry maps phase names to their output struct types.
var registry = []struct {
	Phase string
	Type  reflect.Type
}{
	{"triage", reflect.TypeOf(schemas.TriageOutput{})},
	{"plan", reflect.TypeOf(schemas.PlanOutput{})},
	{"implement", reflect.TypeOf(schemas.ImplementOutput{})},
	{"verify", reflect.TypeOf(schemas.VerifyOutput{})},
	{"review", reflect.TypeOf(schemas.ReviewOutput{})},
	{"submit", reflect.TypeOf(schemas.SubmitOutput{})},
	{"monitor", reflect.TypeOf(schemas.MonitorOutput{})},
}

func main() {
	type entry struct {
		Phase   string
		VarName string
		Schema  string
	}

	var entries []entry
	for _, reg := range registry {
		schema := generateSchema(reg.Type)
		raw, err := json.Marshal(schema)
		if err != nil {
			fmt.Fprintf(os.Stderr, "schemagen: marshal %s: %v\n", reg.Phase, err)
			os.Exit(1)
		}
		entries = append(entries, entry{
			Phase:   reg.Phase,
			VarName: schemaVarName(reg.Phase),
			Schema:  string(raw),
		})
	}

	// When invoked by go:generate, GOPACKAGE is set and the working
	// directory is the package directory containing the directive.
	// Default to writing generated.go in the current directory.
	outPath := "generated.go"
	if envPath := os.Getenv("SCHEMAGEN_OUTPUT"); envPath != "" {
		outPath = envPath
	}

	file, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "schemagen: create %s: %v\n", outPath, err)
		os.Exit(1)
	}
	defer file.Close()

	tmpl := template.Must(template.New("generated").Parse(generatedTemplate))
	data := struct {
		Timestamp string
		Entries   []entry
	}{
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Entries:   entries,
	}
	if err := tmpl.Execute(file, data); err != nil {
		fmt.Fprintf(os.Stderr, "schemagen: execute template: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "schemagen: wrote %s (%d schemas)\n", outPath, len(entries))
}

// jsonSchema represents a JSON Schema object.
type jsonSchema struct {
	Type       string                `json:"type"`
	Properties map[string]jsonSchema `json:"properties,omitempty"`
	Items      *jsonSchema           `json:"items,omitempty"`
	Required   []string              `json:"required,omitempty"`
}

// generateSchema builds a JSON Schema from a reflect.Type.
func generateSchema(typ reflect.Type) jsonSchema {
	if typ.Kind() == reflect.Ptr {
		typ = typ.Elem()
	}

	switch typ.Kind() {
	case reflect.String:
		return jsonSchema{Type: "string"}
	case reflect.Bool:
		return jsonSchema{Type: "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return jsonSchema{Type: "integer"}
	case reflect.Float32, reflect.Float64:
		return jsonSchema{Type: "number"}
	case reflect.Slice:
		items := generateSchema(typ.Elem())
		return jsonSchema{Type: "array", Items: &items}
	case reflect.Struct:
		return generateStructSchema(typ)
	default:
		return jsonSchema{Type: "string"}
	}
}

// generateStructSchema builds a JSON Schema object from a struct type.
func generateStructSchema(typ reflect.Type) jsonSchema {
	props := make(map[string]jsonSchema)
	var required []string

	for idx := 0; idx < typ.NumField(); idx++ {
		field := typ.Field(idx)
		if !field.IsExported() {
			continue
		}

		tag := field.Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}

		parts := strings.Split(tag, ",")
		name := parts[0]
		if name == "" {
			continue
		}

		omitempty := false
		for _, opt := range parts[1:] {
			if opt == "omitempty" {
				omitempty = true
			}
		}

		props[name] = generateSchema(field.Type)

		if !omitempty {
			required = append(required, name)
		}
	}

	// Sort required for deterministic output.
	sort.Strings(required)

	return jsonSchema{
		Type:       "object",
		Properties: props,
		Required:   required,
	}
}

// schemaVarName converts a phase name like "triage" to "TriageSchema".
func schemaVarName(phase string) string {
	if phase == "" {
		return "Schema"
	}
	return strings.ToUpper(phase[:1]) + phase[1:] + "Schema"
}

const generatedTemplate = `// Code generated by cmd/schemagen; DO NOT EDIT.
// Generated: {{ .Timestamp }}

package schemas

// Phase output JSON schemas generated from Go struct types.
// These are passed to the Claude CLI via --json-schema.
const (
{{- range .Entries }}
	{{ .VarName }} = ` + "`" + `{{ .Schema }}` + "`" + `
{{- end }}
)
`
